name: quote_generator

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install requests
      - name: Get quote
        run: |
          python python.py
      - name: Commit to update readme
        run: |
          git config --global user.email "duchuy.124dk@gmail.com"
          git config --global user.name "bui-duc-huy"
          git add .
          git commit -m "Updated README.md" || echo "No changes to commit"
          git push
